name: irlib
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - h5py 
  - scipy 
  - matplotlib >= 3.0
  - cython 
  - geopandas >= 1.0
  - vitables 
  - sphinx
  - numpydoc
  - conda-build
